## 端口号  上下文路径
server:
  port: 8081
  servlet:
    context-path: /

## 数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yhdg?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: Yds990320-

  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/
#  redis:
#    # Redis服务器地址
#    host: 192.168.216.186
#    # Redis服务器端口
#    port: 6379
#    # Redis服务器端口
#    password: root
#    # Redis服务器端口
#    database: 0
#    # 连接超时时间
#    timeout: 10000ms
#    lettuce:
#      pool:
#        # 最大连接数，默认8
#        max-active: 1024
#        # 最大连接阻塞等待时间，单位毫秒，默认-1ms
#        max-wait: 10000ms
#        # 最大空闲连接，默认8
#        max-idle: 200
#        # 最小空闲连接，默认0
#        min-idle: 5

  ## 启用热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

## mybatis 配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.Aser5544.YHDG.bean;com.Aser5544.YHDG.query;com.Aser5544.YHDG.dto
  configuration:
    map-underscore-to-camel-case: true

## pageHelper 分页
pagehelper:
  helper-dialect: mysql

## 设置 dao 日志打印级别
logging:
  level:
    com:
      yjxxt:
        crm:
          mapper: debug